language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env: TMPDIR=/tmp

install:
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

services:
  - memcached

before_script:
  - sudo apt-get update
  - sudo pecl install pcs-1.3.3
  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres
  - echo "extension = pcs.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php

matrix:
  allow_failures:
   - php: 7.0
   - php: hhvm
