language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1.11

env: TMPDIR=/tmp

install:
 - phpenv rehash

services:
  - memcached

before_script:
  - set -e

  - phpenv config-rm xdebug.ini || return 0
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then phpenv config-add tests/php7_config.ini; fi

  ##
  #  Setup
  ##
  - sudo apt-get update
  - sudo apt-get install python-httplib2
  - wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb
  - wget http://packages.couchbase.com/releases/4.6.0-DP/couchbase-server-enterprise_4.6.0-DP-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-release-1.0-2-amd64.deb
  - sudo dpkg -i couchbase-server-enterprise_4.6.0-DP-ubuntu14.04_amd64.deb

  # do AFTER couchbase installation
  - sudo apt-get update
  - sudo apt-get install libcouchbase-dev

  # php version specific
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo apt-get install python-software-properties; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo add-apt-repository ppa:ondrej/php -y; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo apt-get update; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo apt-get install php7.0-dev php7.0-intl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sudo apt-get install php7.1-dev php7.1-intl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then sudo apt-get install php5-dev; fi

  # Last installations (pcs before couchbase)
  - pecl install pcs-1.3.3
  - pecl install couchbase-2.2.4
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo apt-get install libmemcached-dev && echo $(pkg-config libmemcached-dev --variable=prefix) | pecl install memcached-3.0.4; fi


  ##
  #  DB
  ##

  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - cd /opt/couchbase
  - ./bin/couchbase-server -- -noinput -detached
  - sleep 20
  - ./bin/couchbase-cli cluster-init -c 127.0.0.1:8091  --cluster-username=Administrator --cluster-password=password --cluster-port=8091 --cluster-index-ramsize=512 --cluster-ramsize=512 --services=data,query,index
  - ./bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=testing --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=512  --bucket-replica=1 -u Administrator -p password
  - sleep 10
  - ./bin/cbq -e http://127.0.0.1:8091 --script "CREATE PRIMARY INDEX ON testing USING GSI;"



  # Back to main dir
  - cd $TRAVIS_BUILD_DIR

  ##
  #  PHP
  ##

  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

  ##
  #  Composer
  ##

  - travis_retry composer install --no-interaction --prefer-source --dev

script:
 - cd tests/
 - php runalltests.php

matrix:
  allow_failures:
   - php: 7.0
